/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnomalyMap: typeof import('./src/components/AnomalyMap.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    RegionDetailedDrawer: typeof import('./src/components/RegionDetailedDrawer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
