/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnomalyMap: typeof import('./src/components/AnomalyMap.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    RegionAnomalies: typeof import('./src/components/RegionDetailedDrawer/RegionAnomalies.vue')['default']
    RegionAnomaliesChart: typeof import('./src/components/RegionDetailedDrawer/RegionAnomaliesChart.vue')['default']
    RegionAnomaliesHistory: typeof import('./src/components/RegionDetailedDrawer/RegionAnomaliesHistory.vue')['default']
    RegionAnomaliesHistoryTable: typeof import('./src/components/RegionDetailedDrawer/RegionAnomaliesHistoryTable.vue')['default']
    RegionAnomaliesTable: typeof import('./src/components/RegionDetailedDrawer/RegionAnomaliesTable.vue')['default']
    RegionDetailedDrawer: typeof import('./src/components/RegionDetailedDrawer/index.vue')['default']
    RegionModelInfo: typeof import('./src/components/RegionDetailedDrawer/RegionModelInfo/index.vue')['default']
    RegionSeasonality: typeof import('./src/components/RegionDetailedDrawer/RegionSeasonality.vue')['default']
    RegionSeasonalityv2: typeof import('./src/components/RegionDetailedDrawer/RegionSeasonalityv2.vue')['default']
    RegionSummary: typeof import('./src/components/RegionDetailedDrawer/RegionSummary.vue')['default']
    RegionTrend: typeof import('./src/components/RegionDetailedDrawer/RegionModelInfo/RegionTrend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
