services:
  data_db:
    image: postgis/postgis:15-3.5
    container_name: anomaly-detection-db
    hostname: db
    volumes:
      - anomaly-detection-db_data:/var/lib/postgresql/data
      - anomaly-detection-db_data_backups:/backups
    env_file:
      - ./api/.envs/.production/.postgres.env
    # command: "-c log_statement=all"

  data_broker:
    image: rabbitmq:4.1.0-management
    hostname: broker
    container_name: anomaly-detection-broker
    volumes:
      - anomaly-detection-broker:/var/lib/rabbitmq

  backend_api: &api
    image:  ghcr.io/mosquito-alert/anomaly_detection-api:0.1.6
    container_name: anomaly-detection-api
    hostname: api
    ports:
      - "8000:5000"
    volumes:
      - ./api/static:/usr/app/static
    env_file:
      - ./api/.envs/.production/.django.env
      - ./api/.envs/.production/.postgres.env
    healthcheck:
      test: "curl -f http://localhost:5000/ping/ || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - data_db
      - data_broker

  backend_worker:
    <<: *api
    container_name: anomaly-detection-worker
    hostname: worker
    ports: []
    command: /scripts/start_worker
    healthcheck:
      test: "/entrypoint celery inspect ping -d celery@$$HOSTNAME"


  backend_worker_flower:
    <<: *api
    container_name: anomaly-detection-flower
    hostname: flower
    ports:
      - "5555:5555"
    command: /scripts/start_flower
    healthcheck:
      disable: true

  frontend:
    image: ghcr.io/mosquito-alert/anomaly_detection-frontend:0.1.4
    container_name: anomaly-detection-frontend
    hostname: frontend
    ports:
      - "9000:80"
    environment:
      - VUE_APP_API_URL=https://metrics.mosquitoalert.com/api
      - VUE_APP_API_VERSION=v1
    depends_on:
      - backend_api

volumes:
  anomaly-detection-db_data:
  anomaly-detection-db_data_backups:
  anomaly-detection-broker:
    driver: local


