services:
  api:
    build:
      context: ./api
      args:
        - DEV=true
    image: mosquito-alert/anomaly-detection-local-api
    container_name: anomaly-detection-local-api
    hostname: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/app
    env_file:
      - ./api/.envs/.local/.django.env
      - ./api/.envs/.local/.postgres.env
    # healthcheck:
    #   test: "curl -f http://localhost:8000/ping/ || exit 1"
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
    depends_on:
      - db

  db:
    image: postgis/postgis:17-3.5 # 12.3. # TODO: Downgrade a Postgres 15
    container_name: anomaly-detection-local-db
    hostname: db
    ports:
      - "5432:5432"
    volumes:
      - anomaly-detection-local-db_data:/var/lib/postgresql/data
      - anomaly-detection-local-db_data_backups:/backups
    env_file:
      - ./api/.envs/.local/.postgres.env

volumes:
  anomaly-detection-local-db_data:
  anomaly-detection-local-db_data_backups:
