#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py collectstatic --noinput
python manage.py wait_for_db
python manage.py migrate
exec /usr/local/bin/gunicorn anomaly_detection.project.wsgi --bind 0.0.0.0:5000 --chdir=/usr/app