# Generated by Django 5.2 on 2025-05-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual_value', models.FloatField()),
                ('predicted_value', models.FloatField()),
                ('lower_value', models.FloatField()),
                ('upper_value', models.FloatField()),
                ('trend', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('importance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_vri', to='geo.municipality', unique_for_date='date')),
            ],
            options={
                'verbose_name': 'Vector Risk Index',
                'verbose_name_plural': 'Vector Risk Indexes',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='vri_vri_date_fb8a64_idx'), models.Index(fields=['region', 'date'], name='vri_vri_region__42859f_idx')],
                'unique_together': {('region', 'date')},
            },
        ),
        migrations.CreateModel(
            name='VRISeasonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField()),
                ('yearly_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonalities', to='geo.municipality')),
            ],
            options={
                'verbose_name': 'VRI Seasonality',
                'verbose_name_plural': 'VRI Seasonalities',
                'ordering': ['index'],
                'indexes': [models.Index(fields=['index'], name='vri_vriseas_index_00fbe2_idx')],
            },
        ),
    ]
